//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIzm.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineParam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MachineParam()
        {
            this.Machine = new HashSet<Machine>();
            this.MachineParam1 = new HashSet<MachineParam>();
            this.ParamInMachine = new HashSet<ParamInMachine>();
        }
    
        public int ID { get; set; }
        public int MachineParamTypeID { get; set; }
        public string DefaultLinkContext { get; set; }
        public string Name { get; set; }
        public Nullable<int> DefaultColor { get; set; }
        public Nullable<int> Num { get; set; }
        public string Description { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Code { get; set; }
        public string MeasureUnit { get; set; }
        public Nullable<int> IsDel { get; set; }
        public int IsByShedule { get; set; }
        public int IsServiceState { get; set; }
        public int IsTakeOffAtStartProgram { get; set; }
        public int AdditionalTypeId { get; set; }
        public int IsDragWhenNoConnect { get; set; }
        public int IsCounter { get; set; }
        public int IsResetAfterShiftChange { get; set; }
        public string IntegrationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine> Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineParam> MachineParam1 { get; set; }
        public virtual MachineParam MachineParam2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParamInMachine> ParamInMachine { get; set; }
    }
}
