//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIzm.Model.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndustryDBEntities1 : DbContext
    {
        public IndustryDBEntities1()
            : base("name=IndustryDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<MachineParam> MachineParam { get; set; }
        public virtual DbSet<ParamInMachine> ParamInMachine { get; set; }
        public virtual DbSet<OperatingProgramExecutionLog> OperatingProgramExecutionLog { get; set; }
    }
}
