//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIzm.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingProgramExecutionLog
    {
        public int Id { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> FileUpId { get; set; }
        public Nullable<int> MonitoringValueId { get; set; }
        public string NameUP { get; set; }
        public System.DateTime DtStart { get; set; }
        public Nullable<System.DateTime> DtEnd { get; set; }
        public Nullable<decimal> ProcessingTime { get; set; }
        public Nullable<decimal> HighSpeedTime { get; set; }
        public Nullable<decimal> MstFucnTime { get; set; }
        public Nullable<decimal> StopTime { get; set; }
        public Nullable<decimal> AvgPercentCorrectFeed { get; set; }
        public Nullable<decimal> AvgPercentCorrectSpeed { get; set; }
        public int ExecutionUpStatusTypeId { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
