//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIzm.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamInMachine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParamInMachine()
        {
            this.Machine = new HashSet<Machine>();
            this.Machine1 = new HashSet<Machine>();
        }
    
        public int ID { get; set; }
        public string LinkContext { get; set; }
        public Nullable<int> LastValueID { get; set; }
        public Nullable<int> ServiceCode { get; set; }
        public string FormulaText { get; set; }
        public string CalcFormula { get; set; }
        public Nullable<double> CalcKoeff { get; set; }
        public Nullable<int> StartTimeOut { get; set; }
        public Nullable<int> EndTimeOut { get; set; }
        public Nullable<double> CalcDelta { get; set; }
        public int CalcTypeID { get; set; }
        public int IsCalcDetail { get; set; }
        public Nullable<int> kProtocolTypeID { get; set; }
        public Nullable<int> DelayTime { get; set; }
        public int IsDetailMadeItogCounter { get; set; }
        public int IsInputByHand { get; set; }
        public int IsPersecondMonitoring { get; set; }
        public int IsForTransfer { get; set; }
        public Nullable<int> MachineProtocolID { get; set; }
        public string Description { get; set; }
        public int IsSendOutputSignal { get; set; }
        public int IsStopIdleTvv { get; set; }
        public Nullable<int> ProtocolId { get; set; }
        public string StateFormulaText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine> Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine> Machine1 { get; set; }
        public virtual Machine Machine2 { get; set; }
        public virtual MachineParam MachineParam { get; set; }
    }
}
